### ISSUE TITLE
mean, std?

### ISSUE THREAD

**Issue by srrk-GreenMan** [batuhan3526/ResNet50_on_Cifar_100_Without_Transfer_Learning#1]
Hi, I saw your ResNet50 codes. It was great but I was wondering the Normalization codes

I don't understand the reason why the mean, std  are divided 255. 

```
transforms.ToTensor(),
transforms.Normalize(mean=[x / 255.0 for x in[0.507, 0.487, 0.441]],
                                     std=[x / 255.0 for x in [0.267, 0.256, 0.276]])
```

As I know about the toTensor methods, it already changes [0, ~ 255.] to [0, 1].

**Comment by batuhan3526** [comment]
You are quite right. While writing this code, I was a little sleepless. It must have come to my carelessness. Thank you for warning me <3
